### ISSUE TITLE
Bug: Rarely, the number of goals jumps up by a high amount

### ISSUE THREAD

**Issue by Timmeey86** [Timmeey86/CustomTrainingStatisticsPlugin#24]
![Bug](https://user-images.githubusercontent.com/10223149/150601056-f9812d90-0e06-42d2-93e2-558d67dd3c83.png)

Reproducer:
Shoot an own goal in custom training

**Comment by BrandonMcBride4** [comment]
It counts up every tick that the ball is in the blue goal, even while the ball is exploding. It stops counting up when the replay starts or when the ball exits the blue goal.

**Comment by Timmeey86** [comment]
It would be easy to exclude everything after the first goal per attempt. However, a proper fix would not count an own goal at all (If anything, we could decrement the goal counter in that case lol)
