### ISSUE TITLE
Bug: Goal/Miss streak prolonged/reset in per shot statistics when changing shot

### ISSUE THREAD

**Issue by BrandonMcBride4** [Timmeey86/CustomTrainingStatisticsPlugin#25]
The goal/miss streak in per shot statistics can be prolonged/accidently reset when changing the shot and coming back to the original shot.

Steps to reproduce:
1. Make streak on shot 1 is greater than or equal to 1
2. Miss the shot (breaking the streak), but before the next attempt starts, change to shot 2.
3. Make a shot on shot 2 and before it the next attempt starts, change back to shot 1.
4. Shot 1's streak is not reset in the beginning of the next attempt

**Comment by Timmeey86** [comment]
@BrandonMcBride4 Can you confirm that this no longer happens with the current `main` branch?
