### ISSUE TITLE
Bug: activating pov view while viewing goal replay makes latest goal speed to 0

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/CustomTrainingStatisticsPlugin#47]
How to reproduce:

Bind Delete "toggle cl_goalreplay_pov 0 1" 

Open a custom training and make a goal with speed > 0 then watch the replay.  While viewing the replay, press delete to switch to pov view. Reset the shot before the replay ends. 

Switching from pov to standard while viewing a goal replay should also make latest goal speed to 0.

**Comment by Timmeey86** [comment]
Bug seems fixed. If you want to have the fix early, you can download the DLL from https://github.com/Timmeey86/CustomTrainingStatisticsPlugin/releases/tag/v1.2.3.651 and place it in your `%APPDATA%\bakkesmod\bakkesmod\plugins` folder manually
