### ISSUE TITLE
Feature: more control what happens when unchecking "enable plugin"

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/CustomTrainingStatisticsPlugin#49]
Currently unchecking "enable plugin" just hides everything but the stats are still recorded. Maybe have the following actions: pause and hide? Pausing should just stop recording and keep graphics visible. Hiding keeps recording on but hides graphics. 

Pausing should be temporary if notifications cannot be used, because otherwise one can accidentally play and assume that stats are recorded. But maybe there is also need to permanent pause because sometimes I don't want to overwrite my last session. 

If performance isn't much impacted, then maybe display always something on the screen when recording is on. And when recording is off, then nothing is displayed. Some users may want to hide stats and view them later, but in that case some small icon should be displayed to indicate that the plugin is still active.

**Comment by Timmeey86** [comment]
I should be able to do this easily after finishing #38

**Comment by Timmeey86** [comment]
@maggaou Would this be suitable?
![grafik](https://user-images.githubusercontent.com/10223149/156173313-2f21e5ce-ffdb-425f-a7e2-8b47519abb6a.png)

**Comment by Timmeey86** [comment]
Options would be like so:
![grafik](https://user-images.githubusercontent.com/10223149/156175575-f481e45a-898c-4eb7-a85a-7fdd7d47d49d.png)

**Comment by maggaou** [comment]
> @maggaou Would this be suitable? ![grafik](https://user-images.githubusercontent.com/10223149/156173313-2f21e5ce-ffdb-425f-a7e2-8b47519abb6a.png)

Yes it is very nice. 

I'm not sure if implemented yet, but tracking everything in the background is a new feature in sense that if I set 

customtrainingstatistics_display_max_goal_speed 0 
(etc)
Then max goal speed is not tracked. I think background tracking should include everything regardless display options. What may be useful is to select to hide different stats in the summary panel. This way I can avoid copying things that I don't want.

**Comment by Timmeey86** [comment]
Right now you can only decide between recording or not recording all stats, and displaying or not displaying the stats you selected. I feel like most people would actually want to record stats which are currently not displayed, so they can display them at the end of the training session, but not during the session.
About the summary panel, it will display exactly the stats that you are currently displaying
