### ISSUE TITLE
Bug: rec icon is stuck

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/CustomTrainingStatisticsPlugin#62]
I set customtrainingstatistics_enable_stat_recording 0 or 1 but the rec icon is stuck and doesn't disappear. Restarting the training doesn't help. 

I think rec icon isn't necessary because one can bind 

toggle customtrainingstatistics_enable_stat_display 0 1

and maybe stat display can include the information if recording is paused. One can then press only one button to check if recording is active or not

The recording itself can be paused and continued but the rec icon isn't working.

**Comment by Timmeey86** [comment]
Are you setting these things manually in the console?
It works for me, at least as long as I use the checkboxes in the General area of the settings menu

**Comment by Timmeey86** [comment]
I see what you mean now. You mean when you enable the icon, but disable both stat recording and the stat display.
Yeah I didn't think of that case.
