### ISSUE TITLE
Bug: customtrainingstatistics_display_total_success_rate 

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/CustomTrainingStatisticsPlugin#63]
running customtrainingstatistics_display_total_success_rate 1 displays current streaks and customtrainingstatistics_display_current_streaks 1 displays total success rate

**Comment by Timmeey86** [comment]
Yeah looks like that was switched by accident. It's just the wrong names, though.
I wonder: Why do you set everything in console rather than through the settings UI?

**Comment by maggaou** [comment]
> I wonder: Why do you set everything in console rather than through the settings UI?

That's a good question. I use different presets for each training pack. This also includes variation settings and mirroring.

**Comment by Timmeey86** [comment]
I created a release which contains the two bug fixes for #63 and #62
https://github.com/Timmeey86/CustomTrainingStatisticsPlugin/releases/tag/v1.3.1.976
