### ISSUE TITLE
Bug: negative green minus signs

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/CustomTrainingStatisticsPlugin#74]
Median and mean speeds difference is displayed incorrectly? 

![](https://i.imgur.com/w7xJEfZ.png)

**Comment by maggaou** [comment]
Also std dev goal speed difference has green minus signs
![](https://i.imgur.com/1kRXMUH.png)

**Comment by Timmeey86** [comment]
This will be fixed in the next update. It currently affects negative values between -0,01 and -0,99 if your regional settings use a comma instead of a decimal point. (In English, it would be -0.09 instead of -0,09 for example)
