### ISSUE TITLE
Bug: typing to console is broken (v1.4.0.1085)

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/CustomTrainingStatisticsPlugin#79]
Using the console while playing in a training pack is not possible. Typing focus switches in/out constantly.

**Comment by Timmeey86** [comment]
Sorry, I can't reproduce this on my machine. Can you try and disable all other plugins and see if it still happens?

**Comment by Timmeey86** [comment]
Most importantly, does it still happen if you disable my plugin?

**Comment by maggaou** [comment]
Disabling the plugin doesn't cause the issue. Also using 1.3.1.976 doesn't cause the issue. This means that 1.4.0.1085 has something that is causing the issue.

I can test with default BM settings if you can provide instructions how to backup everything and then restore default settings.

**Comment by Timmeey86** [comment]
The best chance to find out the issue would probably bea crash dump file.
Can you check if there is a .dmp file in your `My Documents/My Games/rocketleague/TAGame/Logs` folder?
If so, please upload it somewhere (not sure if it works here in GitHub) or try sending it to me in discord (Timmeey86#5290)

**Comment by maggaou** [comment]
[dmp.zip](https://github.com/Timmeey86/CustomTrainingStatisticsPlugin/files/8370705/dmp.zip)

**Comment by Timmeey86** [comment]
I'm sorry, I need to ask you to download the new release, reproduce the crash, then send me the new dump again.
Unfortunately I'm missing a file required for debugging the crash dump you will send, but I made sure I keep the one for the new version:
https://github.com/Timmeey86/CustomTrainingStatisticsPlugin/releases/tag/v1.4.0.1086
You only have to download the DLL as usual

**Comment by maggaou** [comment]
No crash anymore so issue #80 seems to be fixed.  

Details about issue #79: while in a training pack and the game is not paused, when opening the console and pressing w or s, this input is recognized as the car moving forward or backward. This issue is not present in 1.3.1.976.

**Comment by Timmeey86** [comment]
I'm not sure about the crash issue: The only difference between the previous version and the new one is literally the version number, so the code which lead to the crash is still there, but maybe the configuration changes or something.

About the other issue, I'll try to look into this this evening, though this week be hard to track down probably

**Comment by Timmeey86** [comment]
This release should fix #79 and #80:
https://github.com/Timmeey86/CustomTrainingStatisticsPlugin/releases/tag/v1.4.0.1108

There is a chance that #79 will return in the future, since the code I changed in order to "fix" it has no logical connection to the bug at all, and it might only appear fixed.

**Comment by maggaou** [comment]
Thanks

**Comment by maggaou** [comment]
I still experience this when the heatmap is on (customtrainingstatistics_toggle_heatmap)
